# GitHub Actions
# https://help.github.com/en/articles/configuring-a-workflow
name: Unit test

on: push

jobs:
  dependencies:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      # install a specific version of Node using
      # https://github.com/actions/setup-node
      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # just so we learn about available environment variables GitHub provides
      - name: Print env variables
        run: |
          npm i -g @bahmutov/print-env
          print-env GITHUB

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
            /home/runner/.cache/Cypress
            ./packages/test-mithril-hooks/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm ci --ignore-scripts
          ./node_modules/cypress/bin/cypress install
  test_mithril_hooks:
    runs-on: ubuntu-22.04
    needs: dependencies
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: |
            ./node_modules
            /home/runner/.cache/Cypress
            ./packages/test-mithril-hooks/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: mithril-hooks test
        working-directory: ./packages/test-mithril-hooks
        run: npm run test